### PR TITLE
Add BlueZGattCharacteristic.mtu

### PR DESCRIPTION
**Pull request by rohitsangwan01**
https://github.com/bluez/bluez/blob/master/doc/org.bluez.GattCharacteristic.rst#uint16-mtu-read-only

### CODE REVIEW

**Comment by rohitsangwan01** [comment]
@robert-ancell just signed CLA

**Review by robert-ancell — CHANGES_REQUESTED** [review]
Could you please add this to the 'gatt characteristic' test in `tests/bluez_test.dart`? You will just need to add the MTU property to the test object check it can be read back.

**Comment by rohitsangwan01** [comment]
> Could you please add this to the 'gatt characteristic' test in `tests/bluez_test.dart`? You will just need to add the MTU property to the test object check it can be read back.
 
@robert-ancell  Done, hope that's the only thing required for test

**Review by robert-ancell — APPROVED** [review]
Thanks!

**Comment by robert-ancell** [comment]
Just needs the analyze issue and the test failure in the ci. The test could also be merged into the existing test that reads at the properties - no need for a specialist MTU test.

**Comment by rohitsangwan01** [comment]
@robert-ancell any update on this pr, by when this will be merged ?

**Comment by robert-ancell** [comment]
Hi, I've been away but back now. Change looks good, just fix the analyze/test issues and it's ready to land.

**Comment by rohitsangwan01** [comment]
@robert-ancell tried fixing the analyzer/test issue, and also signed the CLA

**Pull request merged**
