### PR TITLE
Add BlueZGattCharacteristic.acquireWrite

### PR DESCRIPTION
**Pull request by robert-ancell**

### CODE REVIEW

**Comment by Sunbreak** [comment]
A little curious why `bluez` needs to be upgraded to `Dart 2.15+`?

```diff
diff --git a/pubspec.yaml b/pubspec.yaml
index a192894..830398a 100644
--- a/pubspec.yaml
+++ b/pubspec.yaml
@@ -7,7 +7,7 @@ description:
 homepage: https://github.com/canonical/bluez.dart
 
 environment:
-  sdk: '>=2.12.0 <3.0.0'
+  sdk: '>=2.15.0 <3.0.0'
 
 platforms:
   linux:
```

We are working on [Added Linux Support](https://github.com/woodemi/quick_blue/pull/63) and we'd like to keep compatible with `Flutter 2.0.0` & `Dart 2.12.0`

**Comment by jpnurmi** [comment]
> A little curious why `bluez` needs to be upgraded to `Dart 2.15+`?

https://github.com/canonical/dbus.dart/pull/265

**Comment by robert-ancell** [comment]
> We are working on [Added Linux Support](https://github.com/woodemi/quick_blue/pull/63) and we'd like to keep compatible with `Flutter 2.0.0` & `Dart 2.12.0`

Do you know how long you expect to support Flutter 2.0? If you want to stick on an older version we can possibly have a branch that supports that for now.

**Comment by Sunbreak** [comment]
> Do you know how long you expect to support Flutter 2.0? If you want to stick on an older version we can possibly have a branch that supports that for now.

That would be very kind of you :)

We'd like to keep compatible with Flutter version within one year according to https://docs.flutter.dev/development/tools/sdk/releases

- Support Flutter 2.0.x from 3/4/2021 to 5/1/2022
- Support Flutter 2.2.x from 5/19/2021 to 7/2/2022
- Support Flutter 2.5.x from 9/8/2021 to 10/16/2022
- etc

**Comment by robert-ancell** [comment]
OK, we'll support the bluez 0.7 branch until 16 October 2022. You might have to prompt us to backport any required features.

**Pull request merged**
